env:
    - $MAGICK_EXT=imagick
    - $MAGICK_EXT=gmagick
before_script:
    - composer self-update
    - composer install
    - sudo apt-get install graphicsmagick libgraphicsmagick-dev libfreetype6 libfreetype6-dev
    - chmod 755 ./tests/script/install-magick
    - ./tests/script/install-magick
language: php
branches:
  only:
  - master
php:
    - 7.1
script:
    - ./vendor/bin/phpunit
notifications:
    email: false
