before_script:
    - composer self-update
    - composer install
    - chmod 755 ./tests/script/install-imagick
    - ./tests/script/install-imagick
language: php
php:
    - 5.4
    - 5.5
script:
    - ./vendor/bin/phpunit
notifications:
    email: false
