env:
    - IMAGINE_DRIVER=imagick
    - IMAGINE_DRIVER=gmagick
before_script:
    - composer self-update
    - composer install
    - sh -e -c "if [ '$IMAGINE_DRIVER' = 'imagick' ]; then
        printf "\n" | pecl install imagick
      fi"
    - sh -e -c "if [ '$IMAGINE_DRIVER' = 'gmagick' ]; then
        printf "\n" | pecl install gmagick
      fi"
language: php
php:
    - 5.4
    - 5.5
script:
    - ./vendor/bin/phpunit
notifications:
    email: false
