before_script:
    - composer self-update
    - composer install
    - sudo apt-get install php5-imagick
language: php
php:
    - 5.4
    - 5.5
script:
    - ./vendor/bin/phpunit
notifications:
    email: false
