before_script:
    - composer self-update
    - composer install
    - chmod 755 ./tests/script/install-imagick
    - ./tests/script/install-imagick
    - echo "extension=imagick.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
language: php
php:
    - 5.4
    - 5.5
script:
    - ./vendor/bin/phpunit
notifications:
    email: false
