before_script:
    - printf "\n" | pecl install imagick
    - composer self-update
    - composer install
language: php
php:
    - 5.4
    - 5.5
script:
    - ./vendor/bin/phpunit
notifications:
    email: false
