#!/bin/bash
if [ "$MAGICK_EXT" == "imagick" ]; then
    printf "\n" | pecl install imagick
elif [ "$MAGICK_EXT" == "gmagick" ]; then
    if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then
        printf "\n" | pecl install gmagick-1.1.7RC3
    else
        printf "\n" | pecl install gmagick-2.0.4RC1
    fi
fi
