#!/bin/bash
sudo apt-get install -y autoconf automake libtool m4 php5-dev imagemagick libgraphicsmagick1-dev libmagickcore-dev libmagickwand-dev

# install this version
IMAGICK=3.1.2

# compile manually, because `pecl install imagick` keep asking questions
wget http://pecl.php.net/get/imagick-$IMAGICK.tgz
tar zxvf imagick-$IMAGICK.tgz
cd "imagick-${IMAGICK}"
sudo phpize && sudo ./configure && sudo make install && echo "Installed ext/imagick-${IMAGICK}"
