#!/bin/bash
if [ "$MAGICK_EXT" == "imagick" ]; then
    printf "\n" | pecl install imagick
elif [ "$MAGICK_EXT" == "gmagick" ]; then
    sudo apt-get install graphicsmagick libgraphicsmagick-dev
    printf "\n" | pecl install gmagick-1.1.7RC3
fi
